In [2]:
import pandas as pd
import requests
from dotenv import load_dotenv
import os

In [3]:
host = os.getenv('FOOTBALL_API_HOST')
api = os.getenv('FOOTBALL_API_KEY')

headers={'x-apisports-key': api}

### League

In [6]:
target1 = 'leagues'

response = requests.get(url = f'{host}/{target1}', headers=headers)
data = response.json().get('response')

dataframe = pd.json_normalize(data)
dataframe.head()

,seasons,league.id,league.name,league.type,league.logo,country.name,country.code,country.flag
0,"[{'year': 2008, 'start': '2008-06-07', 'end': ...",4,Euro Championship,Cup,https://media.api-sports.io/football/leagues/4...,World,NaN,NaN
1,"[{'year': 2009, 'start': '2009-06-14', 'end': ...",21,Confederations Cup,Cup,https://media.api-sports.io/football/leagues/2...,World,NaN,NaN
2,"[{'year': 2010, 'start': '2010-08-06', 'end': ...",62,Ligue 2,League,https://media.api-sports.io/football/leagues/6...,France,FR,https://media.api-sports.io/flags/fr.svg
3,"[{'year': 2010, 'start': '2010-08-07', 'end': ...",61,Ligue 1,League,https://media.api-sports.io/football/leagues/6...,France,FR,https://media.api-sports.io/flags/fr.svg
4,"[{'year': 2010, 'start': '2010-07-30', 'end': ...",144,Jupiler Pro League,League,https://media.api-sports.io/football/leagues/1...,Belgium,BE,https://media.api-sports.io/flags/be.svg

In [12]:
dataframe

,seasons,league.id,league.name,league.type,league.logo,country.name,country.code,country.flag
0,"[{'year': 2008, 'start': '2008-06-07', 'end': ...",4,Euro Championship,Cup,https://media.api-sports.io/football/leagues/4...,World,NaN,NaN
1,"[{'year': 2009, 'start': '2009-06-14', 'end': ...",21,Confederations Cup,Cup,https://media.api-sports.io/football/leagues/2...,World,NaN,NaN
2,"[{'year': 2010, 'start': '2010-08-06', 'end': ...",62,Ligue 2,League,https://media.api-sports.io/football/leagues/6...,France,FR,https://media.api-sports.io/flags/fr.svg
3,"[{'year': 2010, 'start': '2010-08-07', 'end': ...",61,Ligue 1,League,https://media.api-sports.io/football/leagues/6...,France,FR,https://media.api-sports.io/flags/fr.svg
4,"[{'year': 2010, 'start': '2010-07-30', 'end': ...",144,Jupiler Pro League,League,https://media.api-sports.io/football/leagues/1...,Belgium,BE,https://media.api-sports.io/flags/be.svg
...,...,...,...,...,...,...,...,...
1230,"[{'year': 2026, 'start': '2026-02-06', 'end': ...",1230,Npl Nsw U20,League,https://media.api-sports.io/football/leagues/1...,Australia,AU,https://media.api-sports.io/flags/au.svg
1231,"[{'year': 2026, 'start': '2026-06-01', 'end': ...",1231,Federation Cup,Cup,https://media.api-sports.io/football/leagues/1...,Nigeria,NG,https://media.api-sports.io/flags/ng.svg
1232,"[{'year': 2026, 'start': '2026-06-11', 'end': ...",1232,Copa De La Liga,Cup,https://media.api-sports.io/football/leagues/1...,Peru,PE,https://media.api-sports.io/flags/pe.svg
1233,"[{'year': 2026, 'start': '2026-06-13', 'end': ...",1233,Super Cup Women,Cup,https://media.api-sports.io/football/leagues/1...,Russia,RU,https://media.api-sports.io/flags/ru.svg
1234,"[{'year': 2026, 'start': '2026-03-07', 'end': ...",1234,K4 League,League,https://media.api-sports.io/football/leagues/1...,South-Korea,KR,https://media.api-sports.io/flags/kr.svg

## Countries

In [3]:
target2 = 'countries'
response2 = requests.get(url = f'{host}/{target2}', headers=headers)
data2 = response2.json().get('response')

In [4]:
dataframe2 = pd.DataFrame(data2)
dataframe2.head()

                  name code                                      flag
0              Albania   AL  https://media.api-sports.io/flags/al.svg
1              Algeria   DZ  https://media.api-sports.io/flags/dz.svg
2              Andorra   AD  https://media.api-sports.io/flags/ad.svg
3               Angola   AO  https://media.api-sports.io/flags/ao.svg
4  Antigua-And-Barbuda   AG  https://media.api-sports.io/flags/ag.svg

## Teams

In [9]:
dataframe

,seasons,league.id,league.name,league.type,league.logo,country.name,country.code,country.flag
0,"[{'year': 2008, 'start': '2008-06-07', 'end': ...",4,Euro Championship,Cup,https://media.api-sports.io/football/leagues/4...,World,NaN,NaN
1,"[{'year': 2009, 'start': '2009-06-14', 'end': ...",21,Confederations Cup,Cup,https://media.api-sports.io/football/leagues/2...,World,NaN,NaN
2,"[{'year': 2010, 'start': '2010-08-06', 'end': ...",62,Ligue 2,League,https://media.api-sports.io/football/leagues/6...,France,FR,https://media.api-sports.io/flags/fr.svg
3,"[{'year': 2010, 'start': '2010-08-07', 'end': ...",61,Ligue 1,League,https://media.api-sports.io/football/leagues/6...,France,FR,https://media.api-sports.io/flags/fr.svg
4,"[{'year': 2010, 'start': '2010-07-30', 'end': ...",144,Jupiler Pro League,League,https://media.api-sports.io/football/leagues/1...,Belgium,BE,https://media.api-sports.io/flags/be.svg
...,...,...,...,...,...,...,...,...
1230,"[{'year': 2026, 'start': '2026-02-06', 'end': ...",1230,Npl Nsw U20,League,https://media.api-sports.io/football/leagues/1...,Australia,AU,https://media.api-sports.io/flags/au.svg
1231,"[{'year': 2026, 'start': '2026-06-01', 'end': ...",1231,Federation Cup,Cup,https://media.api-sports.io/football/leagues/1...,Nigeria,NG,https://media.api-sports.io/flags/ng.svg
1232,"[{'year': 2026, 'start': '2026-06-11', 'end': ...",1232,Copa De La Liga,Cup,https://media.api-sports.io/football/leagues/1...,Peru,PE,https://media.api-sports.io/flags/pe.svg
1233,"[{'year': 2026, 'start': '2026-06-13', 'end': ...",1233,Super Cup Women,Cup,https://media.api-sports.io/football/leagues/1...,Russia,RU,https://media.api-sports.io/flags/ru.svg
1234,"[{'year': 2026, 'start': '2026-03-07', 'end': ...",1234,K4 League,League,https://media.api-sports.io/football/leagues/1...,South-Korea,KR,https://media.api-sports.io/flags/kr.svg

In [24]:
prem_index = dataframe.loc[(dataframe['league.name'] == 'Premier League') & (dataframe['country.name'] == 'England') , 'league.id'].to_string(index = False)

In [29]:
target3 = 'teams'

response3 = requests.get(url=f'{host}/{target3}', headers=headers, params={'league': prem_index, 'season': '2022'})
data3 = response3.json().get('response')

data3

[{'team': {'id': 33,
   'name': 'Manchester United',
   'code': 'MUN',
   'country': 'England',
   'founded': 1878,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/33.png'},
  'venue': {'id': 556,
   'name': 'Old Trafford',
   'address': 'Sir Matt Busby Way',
   'city': 'Manchester',
   'capacity': 76212,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/556.png'}},
 {'team': {'id': 34,
   'name': 'Newcastle',
   'code': 'NEW',
   'country': 'England',
   'founded': 1892,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/34.png'},
  'venue': {'id': 562,
   'name': "St. James' Park",
   'address': 'St. James&apos; Street',
   'city': 'Newcastle upon Tyne',
   'capacity': 52758,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/562.png'}},
 {'team': {'id': 35,
   'name': 'Bournemouth',
   'code': 'BOU',
   'country': 'England',
   'founded': 1899,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/35.png'},
  'venue': {'id': 504,
   'name': 'Vitality Stadium',
   'address': 'Dean Court, Kings Park',
   'city': 'Bournemouth, Dorset',
   'capacity': 12000,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/504.png'}},
 {'team': {'id': 36,
   'name': 'Fulham',
   'code': 'FUL',
   'country': 'England',
   'founded': 1879,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/36.png'},
  'venue': {'id': 535,
   'name': 'Craven Cottage',
   'address': 'Stevenage Road',
   'city': 'London',
   'capacity': 29589,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/535.png'}},
 {'team': {'id': 39,
   'name': 'Wolves',
   'code': 'WOL',
   'country': 'England',
   'founded': 1877,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/39.png'},
  'venue': {'id': 600,
   'name': 'Molineux Stadium',
   'address': 'Waterloo Road',
   'city': 'Wolverhampton, West Midlands',
   'capacity': 34624,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/600.png'}},
 {'team': {'id': 40,
   'name': 'Liverpool',
   'code': 'LIV',
   'country': 'England',
   'founded': 1892,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/40.png'},
  'venue': {'id': 550,
   'name': 'Anfield',
   'address': 'Anfield Road',
   'city': 'Liverpool',
   'capacity': 61276,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/550.png'}},
 {'team': {'id': 41,
   'name': 'Southampton',
   'code': 'SOU',
   'country': 'England',
   'founded': 1885,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/41.png'},
  'venue': {'id': 585,
   'name': "St. Mary's Stadium",
   'address': 'Britannia Road',
   'city': 'Southampton, Hampshire',
   'capacity': 32689,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/585.png'}},
 {'team': {'id': 42,
   'name': 'Arsenal',
   'code': 'ARS',
   'country': 'England',
   'founded': 1886,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/42.png'},
  'venue': {'id': 494,
   'name': 'Emirates Stadium',
   'address': 'Hornsey Road',
   'city': 'London',
   'capacity': 60383,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/494.png'}},
 {'team': {'id': 45,
   'name': 'Everton',
   'code': 'EVE',
   'country': 'England',
   'founded': 1878,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/45.png'},
  'venue': {'id': 22033,
   'name': 'Hill Dickinson Stadium',
   'address': '35 Regent Road, Bramley-Moore Dock, Vauxhall',
   'city': 'Liverpool, Merseyside',
   'capacity': 52888,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/22033.png'}},
 {'team': {'id': 46,
   'name': 'Leicester',
   'code': 'LEI',
   'country': 'England',
   'founded': 1884,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/46.png'},
  'venue': {'id': 547,
   'name': 'King Power Stadium',
   'address': 'Filbert Way',
   'city': 'Leicester, Leicestershire',
   'capacity': 34310,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/547.png'}},
 {'team': {'id': 47,
   'name': 'Tottenham',
   'code': 'TOT',
   'country': 'England',
   'founded': 1882,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/47.png'},
  'venue': {'id': 593,
   'name': 'Tottenham Hotspur Stadium',
   'address': 'Bill Nicholson Way, 748 High Road',
   'city': 'London',
   'capacity': 62850,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/593.png'}},
 {'team': {'id': 48,
   'name': 'West Ham',
   'code': 'WES',
   'country': 'England',
   'founded': 1895,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/48.png'},
  'venue': {'id': 598,
   'name': 'London Stadium',
   'address': 'Marshgate Lane, Stratford',
   'city': 'London',
   'capacity': 64472,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/598.png'}},
 {'team': {'id': 49,
   'name': 'Chelsea',
   'code': 'CHE',
   'country': 'England',
   'founded': 1905,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/49.png'},
  'venue': {'id': 519,
   'name': 'Stamford Bridge',
   'address': 'Fulham Road',
   'city': 'London',
   'capacity': 41841,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/519.png'}},
 {'team': {'id': 50,
   'name': 'Manchester City',
   'code': 'MCI',
   'country': 'England',
   'founded': 1880,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/50.png'},
  'venue': {'id': 555,
   'name': 'Etihad Stadium',
   'address': 'Rowsley Street',
   'city': 'Manchester',
   'capacity': 55097,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/555.png'}},
 {'team': {'id': 51,
   'name': 'Brighton',
   'code': 'BRI',
   'country': 'England',
   'founded': 1901,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/51.png'},
  'venue': {'id': 508,
   'name': 'American Express Stadium',
   'address': 'Village Way',
   'city': 'Falmer, East Sussex',
   'capacity': 31872,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/508.png'}},
 {'team': {'id': 52,
   'name': 'Crystal Palace',
   'code': 'CRY',
   'country': 'England',
   'founded': 1861,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/52.png'},
  'venue': {'id': 525,
   'name': 'Selhurst Park',
   'address': 'Holmesdale Road',
   'city': 'London',
   'capacity': 26309,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/525.png'}},
 {'team': {'id': 55,
   'name': 'Brentford',
   'code': 'BRE',
   'country': 'England',
   'founded': 1889,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/55.png'},
  'venue': {'id': 10503,
   'name': 'Gtech Community Stadium',
   'address': '166 Lionel Rd N, Brentford',
   'city': 'Brentford, Middlesex',
   'capacity': 17250,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/10503.png'}},
 {'team': {'id': 63,
   'name': 'Leeds',
   'code': 'LEE',
   'country': 'England',
   'founded': 1919,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/63.png'},
  'venue': {'id': 546,
   'name': 'Elland Road',
   'address': 'Elland Road',
   'city': 'Leeds, West Yorkshire',
   'capacity': 40204,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/546.png'}},
 {'team': {'id': 65,
   'name': 'Nottingham Forest',
   'code': 'NOT',
   'country': 'England',
   'founded': 1865,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/65.png'},
  'venue': {'id': 566,
   'name': 'The City Ground',
   'address': 'Pavilion Road',
   'city': 'Nottingham, Nottinghamshire',
   'capacity': 30576,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/566.png'}},
 {'team': {'id': 66,
   'name': 'Aston Villa',
   'code': 'AST',
   'country': 'England',
   'founded': 1874,
   'national': False,
   'logo': 'https://media.api-sports.io/football/teams/66.png'},
  'venue': {'id': 495,
   'name': 'Villa Park',
   'address': 'Trinity Road',
   'city': 'Birmingham',
   'capacity': 42824,
   'surface': 'grass',
   'image': 'https://media.api-sports.io/football/venues/495.png'}}]

In [30]:
dataframe3 = pd.json_normalize(data3)
dataframe3.head()

,team.id,team.name,team.code,team.country,team.founded,team.national,team.logo,venue.id,venue.name,venue.address,venue.city,venue.capacity,venue.surface,venue.image
0,33,Manchester United,MUN,England,1878,False,https://media.api-sports.io/football/teams/33.png,556,Old Trafford,Sir Matt Busby Way,Manchester,76212,grass,https://media.api-sports.io/football/venues/55...
1,34,Newcastle,NEW,England,1892,False,https://media.api-sports.io/football/teams/34.png,562,St. James' Park,St. James&apos; Street,Newcastle upon Tyne,52758,grass,https://media.api-sports.io/football/venues/56...
2,35,Bournemouth,BOU,England,1899,False,https://media.api-sports.io/football/teams/35.png,504,Vitality Stadium,"Dean Court, Kings Park","Bournemouth, Dorset",12000,grass,https://media.api-sports.io/football/venues/50...
3,36,Fulham,FUL,England,1879,False,https://media.api-sports.io/football/teams/36.png,535,Craven Cottage,Stevenage Road,London,29589,grass,https://media.api-sports.io/football/venues/53...
4,39,Wolves,WOL,England,1877,False,https://media.api-sports.io/football/teams/39.png,600,Molineux Stadium,Waterloo Road,"Wolverhampton, West Midlands",34624,grass,https://media.api-sports.io/football/venues/60...

In [31]:
dataframe3

,team.id,team.name,team.code,team.country,team.founded,team.national,team.logo,venue.id,venue.name,venue.address,venue.city,venue.capacity,venue.surface,venue.image
0,33,Manchester United,MUN,England,1878,False,https://media.api-sports.io/football/teams/33.png,556,Old Trafford,Sir Matt Busby Way,Manchester,76212,grass,https://media.api-sports.io/football/venues/55...
1,34,Newcastle,NEW,England,1892,False,https://media.api-sports.io/football/teams/34.png,562,St. James' Park,St. James&apos; Street,Newcastle upon Tyne,52758,grass,https://media.api-sports.io/football/venues/56...
2,35,Bournemouth,BOU,England,1899,False,https://media.api-sports.io/football/teams/35.png,504,Vitality Stadium,"Dean Court, Kings Park","Bournemouth, Dorset",12000,grass,https://media.api-sports.io/football/venues/50...
3,36,Fulham,FUL,England,1879,False,https://media.api-sports.io/football/teams/36.png,535,Craven Cottage,Stevenage Road,London,29589,grass,https://media.api-sports.io/football/venues/53...
4,39,Wolves,WOL,England,1877,False,https://media.api-sports.io/football/teams/39.png,600,Molineux Stadium,Waterloo Road,"Wolverhampton, West Midlands",34624,grass,https://media.api-sports.io/football/venues/60...
5,40,Liverpool,LIV,England,1892,False,https://media.api-sports.io/football/teams/40.png,550,Anfield,Anfield Road,Liverpool,61276,grass,https://media.api-sports.io/football/venues/55...
6,41,Southampton,SOU,England,1885,False,https://media.api-sports.io/football/teams/41.png,585,St. Mary's Stadium,Britannia Road,"Southampton, Hampshire",32689,grass,https://media.api-sports.io/football/venues/58...
7,42,Arsenal,ARS,England,1886,False,https://media.api-sports.io/football/teams/42.png,494,Emirates Stadium,Hornsey Road,London,60383,grass,https://media.api-sports.io/football/venues/49...
8,45,Everton,EVE,England,1878,False,https://media.api-sports.io/football/teams/45.png,22033,Hill Dickinson Stadium,"35 Regent Road, Bramley-Moore Dock, Vauxhall","Liverpool, Merseyside",52888,grass,https://media.api-sports.io/football/venues/22...
9,46,Leicester,LEI,England,1884,False,https://media.api-sports.io/football/teams/46.png,547,King Power Stadium,Filbert Way,"Leicester, Leicestershire",34310,grass,https://media.api-sports.io/football/venues/54...
10,47,Tottenham,TOT,England,1882,False,https://media.api-sports.io/football/teams/47.png,593,Tottenham Hotspur Stadium,"Bill Nicholson Way, 748 High Road",London,62850,grass,https://media.api-sports.io/football/venues/59...
11,48,West Ham,WES,England,1895,False,https://media.api-sports.io/football/teams/48.png,598,London Stadium,"Marshgate Lane, Stratford",London,64472,grass,https://media.api-sports.io/football/venues/59...
12,49,Chelsea,CHE,England,1905,False,https://media.api-sports.io/football/teams/49.png,519,Stamford Bridge,Fulham Road,London,41841,grass,https://media.api-sports.io/football/venues/51...
13,50,Manchester City,MCI,England,1880,False,https://media.api-sports.io/football/teams/50.png,555,Etihad Stadium,Rowsley Street,Manchester,55097,grass,https://media.api-sports.io/football/venues/55...
14,51,Brighton,BRI,England,1901,False,https://media.api-sports.io/football/teams/51.png,508,American Express Stadium,Village Way,"Falmer, East Sussex",31872,grass,https://media.api-sports.io/football/venues/50...
15,52,Crystal Palace,CRY,England,1861,False,https://media.api-sports.io/football/teams/52.png,525,Selhurst Park,Holmesdale Road,London,26309,grass,https://media.api-sports.io/football/venues/52...
16,55,Brentford,BRE,England,1889,False,https://media.api-sports.io/football/teams/55.png,10503,Gtech Community Stadium,"166 Lionel Rd N, Brentford","Brentford, Middlesex",17250,grass,https://media.api-sports.io/football/venues/10...
17,63,Leeds,LEE,England,1919,False,https://media.api-sports.io/football/teams/63.png,546,Elland Road,Elland Road,"Leeds, West Yorkshire",40204,grass,https://media.api-sports.io/football/venues/54...
18,65,Nottingham Forest,NOT,England,1865,False,https://media.api-sports.io/football/teams/65.png,566,The City Ground,Pavilion Road,"Nottingham, Nottinghamshire",30576,grass,https://media.api-sports.io/football/venues/56...
19,66,Aston Villa,AST,England,1874,False,https://media.api-sports.io/football/teams/66.png,495,Villa Park,Trinity Road,Birmingham,42824,grass,https://media.api-sports.io/football/venues/49...

## Matchday

In [5]:
target4 = 'fixtures'
response4 = requests.get(url=f'{host}/{target4}', headers=headers, params={'league': 39, 'season': '2022'})
data4 = response4.json().get('response')
data4

[{'fixture': {'id': 867946,
   'referee': 'A. Taylor',
   'timezone': 'UTC',
   'date': '2022-08-05T19:00:00+00:00',
   'timestamp': 1659726000,
   'periods': {'first': 1659726000, 'second': 1659729600},
   'venue': {'id': 525, 'name': 'Selhurst Park', 'city': 'London'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 1',
   'standings': True},
  'teams': {'home': {'id': 52,
    'name': 'Crystal Palace',
    'logo': 'https://media.api-sports.io/football/teams/52.png',
    'winner': False},
   'away': {'id': 42,
    'name': 'Arsenal',
    'logo': 'https://media.api-sports.io/football/teams/42.png',
    'winner': True}},
  'goals': {'home': 0, 'away': 2},
  'score': {'halftime': {'home': 0, 'away': 1},
   'fulltime': {'home': 0, 'away': 2},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867947,
   'referee': 'A. Madley',
   'timezone': 'UTC',
   'date': '2022-08-06T11:30:00+00:00',
   'timestamp': 1659785400,
   'periods': {'first': 1659785400, 'second': 1659789000},
   'venue': {'id': 535, 'name': 'Craven Cottage', 'city': 'London'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 1',
   'standings': True},
  'teams': {'home': {'id': 36,
    'name': 'Fulham',
    'logo': 'https://media.api-sports.io/football/teams/36.png',
    'winner': None},
   'away': {'id': 40,
    'name': 'Liverpool',
    'logo': 'https://media.api-sports.io/football/teams/40.png',
    'winner': None}},
  'goals': {'home': 2, 'away': 2},
  'score': {'halftime': {'home': 1, 'away': 0},
   'fulltime': {'home': 2, 'away': 2},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867951,
   'referee': 'S. Hooper',
   'timezone': 'UTC',
   'date': '2022-08-06T14:00:00+00:00',
   'timestamp': 1659794400,
   'periods': {'first': 1659794400, 'second': 1659798000},
   'venue': {'id': 562,
    'name': "St. James' Park",
    'city': 'Newcastle upon Tyne'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 1',
   'standings': True},
  'teams': {'home': {'id': 34,
    'name': 'Newcastle',
    'logo': 'https://media.api-sports.io/football/teams/34.png',
    'winner': True},
   'away': {'id': 65,
    'name': 'Nottingham Forest',
    'logo': 'https://media.api-sports.io/football/teams/65.png',
    'winner': False}},
  'goals': {'home': 2, 'away': 0},
  'score': {'halftime': {'home': 0, 'away': 0},
   'fulltime': {'home': 2, 'away': 0},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867948,
   'referee': 'P. Bankes',
   'timezone': 'UTC',
   'date': '2022-08-06T14:00:00+00:00',
   'timestamp': 1659794400,
   'periods': {'first': 1659794400, 'second': 1659798000},
   'venue': {'id': 504,
    'name': 'Vitality Stadium',
    'city': 'Bournemouth, Dorset'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 1',
   'standings': True},
  'teams': {'home': {'id': 35,
    'name': 'Bournemouth',
    'logo': 'https://media.api-sports.io/football/teams/35.png',
    'winner': True},
   'away': {'id': 66,
    'name': 'Aston Villa',
    'logo': 'https://media.api-sports.io/football/teams/66.png',
    'winner': False}},
  'goals': {'home': 2, 'away': 0},
  'score': {'halftime': {'home': 1, 'away': 0},
   'fulltime': {'home': 2, 'away': 0},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867952,
   'referee': 'A. Marriner',
   'timezone': 'UTC',
   'date': '2022-08-06T14:00:00+00:00',
   'timestamp': 1659794400,
   'periods': {'first': 1659794400, 'second': 1659798000},
   'venue': {'id': 593, 'name': 'Tottenham Hotspur Stadium', 'city': 'London'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 1',
   'standings': True},
  'teams': {'home': {'id': 47,
    'name': 'Tottenham',
    'logo': 'https://media.api-sports.io/football/teams/47.png',
    'winner': True},
   'away': {'id': 41,
    'name': 'Southampton',
    'logo': 'https://media.api-sports.io/football/teams/41.png',
    'winner': False}},
  'goals': {'home': 4, 'away': 1},
  'score': {'halftime': {'home': 2, 'away': 1},
   'fulltime': {'home': 4, 'away': 1},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867949,
   'referee': 'R. Jones',
   'timezone': 'UTC',
   'date': '2022-08-06T14:00:00+00:00',
   'timestamp': 1659794400,
   'periods': {'first': 1659794400, 'second': 1659798000},
   'venue': {'id': 546,
    'name': 'Elland Road',
    'city': 'Leeds, West Yorkshire'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 1',
   'standings': True},
  'teams': {'home': {'id': 63,
    'name': 'Leeds',
    'logo': 'https://media.api-sports.io/football/teams/63.png',
    'winner': True},
   'away': {'id': 39,
    'name': 'Wolves',
    'logo': 'https://media.api-sports.io/football/teams/39.png',
    'winner': False}},
  'goals': {'home': 2, 'away': 1},
  'score': {'halftime': {'home': 1, 'away': 1},
   'fulltime': {'home': 2, 'away': 1},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867953,
   'referee': 'C. Pawson',
   'timezone': 'UTC',
   'date': '2022-08-06T16:30:00+00:00',
   'timestamp': 1659803400,
   'periods': {'first': 1659803400, 'second': 1659807000},
   'venue': {'id': 8560, 'name': 'Goodison Park', 'city': 'Liverpool'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 1',
   'standings': True},
  'teams': {'home': {'id': 45,
    'name': 'Everton',
    'logo': 'https://media.api-sports.io/football/teams/45.png',
    'winner': False},
   'away': {'id': 49,
    'name': 'Chelsea',
    'logo': 'https://media.api-sports.io/football/teams/49.png',
    'winner': True}},
  'goals': {'home': 0, 'away': 1},
  'score': {'halftime': {'home': 0, 'away': 1},
   'fulltime': {'home': 0, 'away': 1},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867954,
   'referee': 'P. Tierney',
   'timezone': 'UTC',
   'date': '2022-08-07T13:00:00+00:00',
   'timestamp': 1659877200,
   'periods': {'first': 1659877200, 'second': 1659880800},
   'venue': {'id': 556, 'name': 'Old Trafford', 'city': 'Manchester'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 1',
   'standings': True},
  'teams': {'home': {'id': 33,
    'name': 'Manchester United',
    'logo': 'https://media.api-sports.io/football/teams/33.png',
    'winner': False},
   'away': {'id': 51,
    'name': 'Brighton',
    'logo': 'https://media.api-sports.io/football/teams/51.png',
    'winner': True}},
  'goals': {'home': 1, 'away': 2},
  'score': {'halftime': {'home': 0, 'away': 2},
   'fulltime': {'home': 1, 'away': 2},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867950,
   'referee': 'J. Gillett',
   'timezone': 'UTC',
   'date': '2022-08-07T13:00:00+00:00',
   'timestamp': 1659877200,
   'periods': {'first': 1659877200, 'second': 1659880800},
   'venue': {'id': 547,
    'name': 'King Power Stadium',
    'city': 'Leicester, Leicestershire'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 1',
   'standings': True},
  'teams': {'home': {'id': 46,
    'name': 'Leicester',
    'logo': 'https://media.api-sports.io/football/teams/46.png',
    'winner': None},
   'away': {'id': 55,
    'name': 'Brentford',
    'logo': 'https://media.api-sports.io/football/teams/55.png',
    'winner': None}},
  'goals': {'home': 2, 'away': 2},
  'score': {'halftime': {'home': 1, 'away': 0},
   'fulltime': {'home': 2, 'away': 2},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867955,
   'referee': 'M. Oliver',
   'timezone': 'UTC',
   'date': '2022-08-07T15:30:00+00:00',
   'timestamp': 1659886200,
   'periods': {'first': 1659886200, 'second': 1659889800},
   'venue': {'id': 598, 'name': 'London Stadium', 'city': 'London'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 1',
   'standings': True},
  'teams': {'home': {'id': 48,
    'name': 'West Ham',
    'logo': 'https://media.api-sports.io/football/teams/48.png',
    'winner': False},
   'away': {'id': 50,
    'name': 'Manchester City',
    'logo': 'https://media.api-sports.io/football/teams/50.png',
    'winner': True}},
  'goals': {'home': 0, 'away': 2},
  'score': {'halftime': {'home': 0, 'away': 1},
   'fulltime': {'home': 0, 'away': 2},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867957,
   'referee': 'M. Oliver',
   'timezone': 'UTC',
   'date': '2022-08-13T11:30:00+00:00',
   'timestamp': 1660390200,
   'periods': {'first': 1660390200, 'second': 1660393800},
   'venue': {'id': 495, 'name': 'Villa Park', 'city': 'Birmingham'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 2',
   'standings': True},
  'teams': {'home': {'id': 66,
    'name': 'Aston Villa',
    'logo': 'https://media.api-sports.io/football/teams/66.png',
    'winner': True},
   'away': {'id': 45,
    'name': 'Everton',
    'logo': 'https://media.api-sports.io/football/teams/45.png',
    'winner': False}},
  'goals': {'home': 2, 'away': 1},
  'score': {'halftime': {'home': 1, 'away': 0},
   'fulltime': {'home': 2, 'away': 1},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867965,
   'referee': 'J. Brooks',
   'timezone': 'UTC',
   'date': '2022-08-13T14:00:00+00:00',
   'timestamp': 1660399200,
   'periods': {'first': 1660399200, 'second': 1660402800},
   'venue': {'id': 600,
    'name': 'Molineux Stadium',
    'city': 'Wolverhampton, West Midlands'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 2',
   'standings': True},
  'teams': {'home': {'id': 39,
    'name': 'Wolves',
    'logo': 'https://media.api-sports.io/football/teams/39.png',
    'winner': None},
   'away': {'id': 36,
    'name': 'Fulham',
    'logo': 'https://media.api-sports.io/football/teams/36.png',
    'winner': None}},
  'goals': {'home': 0, 'away': 0},
  'score': {'halftime': {'home': 0, 'away': 0},
   'fulltime': {'home': 0, 'away': 0},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867964,
   'referee': 'T. Harrington',
   'timezone': 'UTC',
   'date': '2022-08-13T14:00:00+00:00',
   'timestamp': 1660399200,
   'periods': {'first': 1660399200, 'second': 1660402800},
   'venue': {'id': 585,
    'name': "St. Mary's Stadium",
    'city': 'Southampton, Hampshire'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 2',
   'standings': True},
  'teams': {'home': {'id': 41,
    'name': 'Southampton',
    'logo': 'https://media.api-sports.io/football/teams/41.png',
    'winner': None},
   'away': {'id': 63,
    'name': 'Leeds',
    'logo': 'https://media.api-sports.io/football/teams/63.png',
    'winner': None}},
  'goals': {'home': 2, 'away': 2},
  'score': {'halftime': {'home': 0, 'away': 0},
   'fulltime': {'home': 2, 'away': 2},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867956,
   'referee': 'D. England',
   'timezone': 'UTC',
   'date': '2022-08-13T14:00:00+00:00',
   'timestamp': 1660399200,
   'periods': {'first': 1660399200, 'second': 1660402800},
   'venue': {'id': 494, 'name': 'Emirates Stadium', 'city': 'London'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 2',
   'standings': True},
  'teams': {'home': {'id': 42,
    'name': 'Arsenal',
    'logo': 'https://media.api-sports.io/football/teams/42.png',
    'winner': True},
   'away': {'id': 46,
    'name': 'Leicester',
    'logo': 'https://media.api-sports.io/football/teams/46.png',
    'winner': False}},
  'goals': {'home': 4, 'away': 2},
  'score': {'halftime': {'home': 2, 'away': 0},
   'fulltime': {'home': 4, 'away': 2},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867962,
   'referee': 'D. Coote',
   'timezone': 'UTC',
   'date': '2022-08-13T14:00:00+00:00',
   'timestamp': 1660399200,
   'periods': {'first': 1660399200, 'second': 1660402800},
   'venue': {'id': 555, 'name': 'Etihad Stadium', 'city': 'Manchester'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 2',
   'standings': True},
  'teams': {'home': {'id': 50,
    'name': 'Manchester City',
    'logo': 'https://media.api-sports.io/football/teams/50.png',
    'winner': True},
   'away': {'id': 35,
    'name': 'Bournemouth',
    'logo': 'https://media.api-sports.io/football/teams/35.png',
    'winner': False}},
  'goals': {'home': 4, 'away': 0},
  'score': {'halftime': {'home': 3, 'away': 0},
   'fulltime': {'home': 4, 'away': 0},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867959,
   'referee': 'G. Scott',
   'timezone': 'UTC',
   'date': '2022-08-13T14:00:00+00:00',
   'timestamp': 1660399200,
   'periods': {'first': 1660399200, 'second': 1660402800},
   'venue': {'id': 508,
    'name': 'The American Express Community Stadium',
    'city': 'Falmer, East Sussex'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 2',
   'standings': True},
  'teams': {'home': {'id': 51,
    'name': 'Brighton',
    'logo': 'https://media.api-sports.io/football/teams/51.png',
    'winner': None},
   'away': {'id': 34,
    'name': 'Newcastle',
    'logo': 'https://media.api-sports.io/football/teams/34.png',
    'winner': None}},
  'goals': {'home': 0, 'away': 0},
  'score': {'halftime': {'home': 0, 'away': 0},
   'fulltime': {'home': 0, 'away': 0},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867958,
   'referee': 'S. Attwell',
   'timezone': 'UTC',
   'date': '2022-08-13T16:30:00+00:00',
   'timestamp': 1660408200,
   'periods': {'first': 1660408200, 'second': 1660411800},
   'venue': {'id': 10503,
    'name': 'Gtech Community Stadium',
    'city': 'Brentford, Middlesex'},
   'status': {'long': 'Match Finished',
    'short': 'FT',
    'elapsed': 90,
    'extra': None}},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media.api-sports.io/football/leagues/39.png',
   'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
   'season': 2022,
   'round': 'Regular Season - 2',
   'standings': True},
  'teams': {'home': {'id': 55,
    'name': 'Brentford',
    'logo': 'https://media.api-sports.io/football/teams/55.png',
    'winner': True},
   'away': {'id': 33,
    'name': 'Manchester United',
    'logo': 'https://media.api-sports.io/football/teams/33.png',
    'winner': False}},
  'goals': {'home': 4, 'away': 0},
  'score': {'halftime': {'home': 4, 'away': 0},
   'fulltime': {'home': 4, 'away': 0},
   'extratime': {'home': None, 'away': None},
   'penalty': {'home': None, 'away': None}}},
 {'fixture': {'id': 867963,
   'referee': 'R. Jones',
   'timezone': 'UTC',
   'date': '2022-08-14T13:00:00+00:00',
   'timestamp': 1660482000,
   'periods': {'first': 1660482000, 'second': 1660485600},
   'venue': {'id': 566,
    'name': 'The City Ground',
    'city': 'Nottingham, Nottinghamshire'},

In [6]:
dataframe4 = pd.json_normalize(data4)
dataframe4

,fixture.id,fixture.referee,fixture.timezone,fixture.date,fixture.timestamp,fixture.periods.first,fixture.periods.second,fixture.venue.id,fixture.venue.name,fixture.venue.city,...,goals.home,goals.away,score.halftime.home,score.halftime.away,score.fulltime.home,score.fulltime.away,score.extratime.home,score.extratime.away,score.penalty.home,score.penalty.away
0,867946,A. Taylor,UTC,2022-08-05T19:00:00+00:00,1659726000,1659726000,1659729600,525,Selhurst Park,London,...,0,2,0,1,0,2,None,None,None,None
1,867947,A. Madley,UTC,2022-08-06T11:30:00+00:00,1659785400,1659785400,1659789000,535,Craven Cottage,London,...,2,2,1,0,2,2,None,None,None,None
2,867951,S. Hooper,UTC,2022-08-06T14:00:00+00:00,1659794400,1659794400,1659798000,562,St. James' Park,Newcastle upon Tyne,...,2,0,0,0,2,0,None,None,None,None
3,867948,P. Bankes,UTC,2022-08-06T14:00:00+00:00,1659794400,1659794400,1659798000,504,Vitality Stadium,"Bournemouth, Dorset",...,2,0,1,0,2,0,None,None,None,None
4,867952,A. Marriner,UTC,2022-08-06T14:00:00+00:00,1659794400,1659794400,1659798000,593,Tottenham Hotspur Stadium,London,...,4,1,2,1,4,1,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,868319,J. Gillett,UTC,2023-05-28T15:30:00+00:00,1685287800,1685287800,1685291400,519,Stamford Bridge,London,...,1,1,1,1,1,1,None,None,None,None
376,868320,T. Bramall,UTC,2023-05-28T15:30:00+00:00,1685287800,1685287800,1685291400,525,Selhurst Park,London,...,1,1,0,1,1,1,None,None,None,None
377,868318,J. Brooks,UTC,2023-05-28T15:30:00+00:00,1685287800,1685287800,1685291400,10503,Gtech Community Stadium,"Brentford, Middlesex",...,1,0,0,0,1,0,None,None,None,None
378,868322,A. Taylor,UTC,2023-05-28T15:30:00+00:00,1685287800,1685287800,1685291400,546,Elland Road,"Leeds, West Yorkshire",...,1,4,0,1,1,4,None,None,None,None
379,868317,D. Coote,UTC,2023-05-28T15:30:00+00:00,1685287800,1685287800,1685291400,495,Villa Park,Birmingham,...,2,1,2,1,2,1,None,None,None,None

In [ ]:
target5 = 'fixture/statistics'
response5 = requests.get(url=f'{host}/{target5}', headers=headers, params={'fixture': '867946', })
data5 = response5.json().get('response')